projects/urls.py
from django.urls import path
from projects.views import project_list, project_detail, project_create, project_edit, project_delete

urlpatterns = [
    path("", project_list, name="list_projects"),
    path("<int:id>/", project_detail, name="show_project"),
    path("create/", project_create, name="create_project"),
    path("delete/<int:id>", project_delete, name="delete_project"),
    path("edit/<int:id>/", project_edit, name="edit_project")
]

tasks/urls.py
from django.urls import path
from tasks.views import task_create, task_delete, task_list, task_edit, project_detail, task_add_notes

urlpatterns = [
    path("create/<int:project_id>", task_create, name="create_task"),
    path("delete/<int:id>", task_delete, name="delete_task"),
    path("mine/", task_list, name="show_my_tasks"),
    path("edit/<int:id>", task_edit, name="edit_task"),
    path("<int:id>/", project_detail, name="show_project"),
    path("add/<int:id>", task_add_notes, name="add_notes")
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_project_list(request):
    return redirect("list_projects")


urlpatterns = [
    path("", redirect_to_project_list, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings
from datetime import date

status_choices = (
    ("1", "Not Started"),
    ("2", "In Progress"),
    ("3", "Complete")
)


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateField(null = True, default = date.today)
    due_date = models.DateField(null = True, default = date.today)
    status = models.CharField(max_length=11, choices=status_choices, default='1')
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True
    )
    team_member = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="projects1"
    )

    def __str__(self):
        return self.name

    def get_team_member(self):
        return ", ".join([f"{user.first_name} {user.last_name}"for user in self.team_member.all()])

projects/forms.py
from django import forms
from django.forms import ModelForm
from projects.models import Project
from django.contrib.auth import get_user_model


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "team_member", "start_date", "due_date", "status"]
        widgets = {
            'start_date': forms.SelectDateWidget(),
            'due_date': forms.SelectDateWidget(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(ProjectForm, self).__init__(*args, **kwargs)

        # Exclude superuser from the assignee choices
        superuser = get_user_model().objects.filter(is_superuser=True).first()
        if user:
            self.fields['team_member'].queryset = get_user_model().objects.exclude(id__in=[user.id, superuser.id])
        else:
            self.fields['team_member'].queryset = get_user_model().objects.exclude(id=superuser.id)

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from projects.models import Project
from projects.forms import ProjectForm
from django.db.models import Q


# Create your views here.
@login_required
def project_list(request):
    projects = Project.objects.filter(Q(owner=request.user)|Q(team_member=request.user)).distinct()
    print('projects', projects)
    context = {
        "project_list": projects,
    }
    return render(request, "projects/list.html", context)


@login_required
def project_detail(request, id):
    details = get_object_or_404(Project, id=id)
    context = {
        "project_detail": details,
    }
    return render(request, "projects/detail.html", context)


@login_required
def project_create(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(False)
            project.owner = request.user
            project.save()
            # created_project_id = project.id

            team_members = request.POST.getlist('team_member')

            for member in team_members:
                project.team_member.add(int(member))

            return redirect("list_projects")
    else:
        form = ProjectForm(user=request.user)
    context = {"form": form}
    return render(request, "projects/create.html", context)

@login_required
def project_edit(request, id):
    print("edit project request", request.POST)
    project = Project.objects.get(id=id)
    if request.method == "POST":
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm(instance=project, user=request.user)
    context = {
            "form": form,
        }
    return render(request, "projects/edit.html", context)

@login_required
def project_delete(request, id):
    project_id = Project.objects.get(id=id)
    if request.method == "POST":
        project_id.delete()
        return redirect("list_projects")

    return render(request, "projects/delete.html")

projects/templates/projects/create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a project</title>
    <link rel="stylesheet" href="{% static 'css/projects.css' %}">
</head>
<body>
    <header>
        <nav class= "nav-items-grid">
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'show_my_tasks' %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url 'list_projects' %}">My projects</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Create Project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
    <footer>
        Projectify by Austin Kim
    </footer>
</body>
</html>

projects/templates/projects/delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete a project</title>
    <link rel="stylesheet" href="{% static 'css/projects.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'show_my_tasks' %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url 'list_projects' %}">My projects</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                <button>Delete</button>
            </form>
        </div>
    </main>
    <footer>
        Projectify by Austin Kim
    </footer>
</body>
</html>

projects/templates/projects/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Tasks</title>
    <link rel="stylesheet" href="{% static 'css/projects.css' %}">
</head>
<body>
    <header>
        <nav class="nav-items-grid">
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'show_my_tasks' %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url 'list_projects' %}">My projects</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1> <span class="shadow-box">{{ project_detail.name }}</span></h1>
            <span class="gray-background">{{ project_detail.description }}</span>
            <table>
                <thead>
                    <th>Owner</th>
                    <th>Team Members</th>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ project_detail.owner }}</td>
                        <td>{{ project_detail.get_team_member}}</td>

                    </tr>
                </tbody>
            </table>
            <h2>Tasks</h2>
            <div>
                <p><a class="pink-background" href="{% url 'create_task' project_detail.id %}">Create a new task</a></p>
            </div>
            {% if project_detail.tasks.count >= 1 %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Status</th>
                        <th>Notes</th>
                    </thead>
                    <tbody>
                        {% for task in project_detail.tasks.all %}
                            <tr>
                                <td>
                                    <div>
                                        <div class="tooltip">
                                        {{ task.name }}
                                        {% if user == project_detail.owner %}
                                        <div class="tooltiptext">
                                            <a href="{% url 'edit_task' task.id %}">Edit</a>
                                            <a href="{% url 'delete_task' task.id %}">Delete</a>
                                        </div>
                                        {% endif %}
                                        </div>
                                    </div>
                                </td>
                                <td>{{ task.assignee }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td class="center-text">{{ task.get_status_display}}</td>
                                <td>{{ task.notes }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="text_color">This project has no tasks</p>
            {% endif %}
        </div>
    </main>
    <footer>
        Projectify by Austin Kim
    </footer>
</body>
</html>

projects/templates/projects/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit a project</title>
    <link rel="stylesheet" href="{% static 'css/projects.css' %}">
</head>
<body>
    <header>
        <nav class= "nav-items-grid">
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'show_my_tasks' %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url 'list_projects' %}">My projects</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Edit Project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Save</button>
            </form>
        </div>
    </main>
    <footer>
        Projectify by Austin Kim
    </footer>
</body>
</html>

projects/templates/projects/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Projects</title>
    <link rel="stylesheet" href="{% static 'css/projects.css' %}">
</head>
<body>
    <header>
        <nav class= "nav-items-grid">
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'show_my_tasks' %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1 class="text-color">{{ user.first_name }}'s Projects</h1>
            <div>
                <p><a class="pink-background" href="{% url 'create_project' %}">Create a new project</a> </p>
            </div>
            {% if project_list.count >= 1 %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of tasks</th>
                        <th>Status</th>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                        <tr>
                            <td>
                                <div>
                                    <div class="tooltip">
                                        <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                        {% if user == project.owner %}
                                        <div class="tooltiptext">
                                            <a href="{% url 'edit_project' project.id %}">Edit</a>
                                            <a href="{% url 'delete_project' project.id %}">Delete</a>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </td>
                            <td class="center-text"> {{ project.tasks.count }} </td>
                            <td class="center-text">{{ project.get_status_display }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="text-color">"You do not have any projects"</p>
            {% endif %}
        </div>
    </main>
    <footer>
        Projectify by Austin Kim
    </footer>
</body>
</html>